### PR TITLE
re-enabled the wpautop function 

### PR DESCRIPTION
**Pull request by rraub**
but it doesn't run for content in shortcodes

### CODE REVIEW

**Comment by idmontie** [comment]
Let me test this before we merge it in.

**Comment by rraub** [comment]
@idmontie have you had a chance to look at this yet?

**Comment by idmontie** [comment]
I will look at it today.

**Comment by idmontie** [comment]
This branch ruins the `/events` page.  Not sure why.  There are extra `<br/>` tags and `<p>` tags everywhere.

**Pull request closed without merging**
